### ISSUE TITLE
Failed to activate the file-types package

### ISSUE THREAD

**Issue by sh4nks** [execjosh/atom-file-types#18]
1. Update from 0.189 to 0.190

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [file-types](https://github.com/execjosh/atom-file-types) package, v0.3.0

### Stack Trace

Failed to activate the file-types package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/peter/.atom/packages/file-types/lib/file-types.coffee:25:33
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:544:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:126:21)
    at Object.module.exports.activate (/Users/peter/.atom/packages/file-types/lib/file-types.coffee:21:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "package-generator",
      "metrics",
      "feedback",
      "deprecation-cop",
      "background-tips",
      "linter-flake8",
      "terminal-panel",
      "autocomplete-plus-jedi",
      "tabs",
      "tree-view"
    ],
    "projectHome": "/Users/peter/Documents/Workspace",
    "audioBeep": false,
    "themes": [
      "unity-ui",
      "atom-dark-syntax"
    ]
  },
  "file-types": {
    "html": "text.html.jinja"
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
autoclose-html, v0.15.0
autocomplete-plus, v2.9.0
autocomplete-plus-python-jedi, v0.2.5
file-types, v0.3.0
linter, v0.12.0
linter-pep8, v0.1.0
project-manager, v1.15.5
sublime-tabs, v0.5.2
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by sh4nks** [comment]
nevermind.. i restarted atom again and now it seems to work
