### ISSUE TITLE
Failed to activate the file-types package

### ISSUE THREAD

**Issue by ascariandrea** [execjosh/atom-file-types#20]
Hi,
I just updated my OS and after restarting I got this error.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [file-types](https://github.com/execjosh/atom-file-types) package, v0.3.0

### Stack Trace

Failed to activate the file-types package

```
At undefined is not a function

TypeError: undefined is not a function
    at /Users/andreaascari/.atom/packages/file-types/lib/file-types.coffee:25:33
    at Config.module.exports.Config.observeKeyPath (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/config.js:544:7)
    at Config.module.exports.Config.observe (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/config.js:126:21)
    at Object.module.exports.activate (/Users/andreaascari/.atom/packages/file-types/lib/file-types.coffee:21:34)
    at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "file-types": {
    "variables": "source.css.less",
    "overrides": "source.css.less"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.6.1
autocomplete-plus, v2.11.0
color-picker, v1.7.0
file-type-icons, v0.5.4
file-types, v0.3.0
language-scala, v1.1.0
linter, v0.12.0
linter-less, v0.3.1
linter-scalac, v0.3.3
minimap, v4.7.6
vim-mode, v0.44.0

# Dev
No dev packages
```

Thanks in advantage.

**Comment by ExcaliburZero** [comment]
I appear to be having the same issue as well when trying out the 1.0 API preview mode:

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: linux 3.19.0-15-generic
**Thrown From**: [file-types](https://github.com/execjosh/atom-file-types) package, v0.3.0

### Stack Trace

Failed to activate the file-types package

```
At undefined is not a function

TypeError: undefined is not a function
    at /home/chris/.atom/packages/file-types/lib/file-types.coffee:25:33
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
    at Object.module.exports.activate (/home/chris/.atom/packages/file-types/lib/file-types.coffee:21:34)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:222:19)
    at /usr/share/atom/resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:434:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:418:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/home/chris/Documents/Code",
    "ignoredNames": [
      ".git",
      ".project",
      ".html~",
      ".md~",
      ".css~",
      ".md~",
      ".txt~"
    ]
  },
  "file-types": {
    "rpy": "source.renpy"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
file-icons, v1.5.4
file-types, v0.3.0
language-lua, v0.9.2
language-renpy, v1.3.0
travis-ci-status, v0.13.0

# Dev
No dev packages
```
