### ISSUE TITLE
Failed to load the file-types package

### ISSUE THREAD

**Issue by Tim1024** [execjosh/atom-file-types#66]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Unknown Windows version
**Thrown From**: [file-types](https://github.com/execjosh/atom-file-types) package 1.0.1

### Stack Trace

Failed to load the file-types package

```
At Cannot find module 'minimatch'

Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/atom-file-types/lib/matcher.coffee:1:15)
    at /packages/atom-file-types/lib/matcher.coffee:1:1)
    at /packages/atom-file-types/lib/matcher.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/atom-file-types/lib/scope-name-provider.coffee:2:11)
    at /packages/atom-file-types/lib/scope-name-provider.coffee:1:1)
    at /packages/atom-file-types/lib/scope-name-provider.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:145675)
    at /packages/atom-file-types/lib/file-types.coffee:1:21)
    at /packages/atom-file-types/lib/file-types.coffee:1:1)
    at /packages/atom-file-types/lib/file-types.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
file-types 1.0.1 
simplified-chinese-menu 5.3.5 
autoclose-html 0.24.0 
autocomplete-paths 2.12.2 
color-picker 2.3.0 
emmet 2.4.3 
emmet 2.4.3 
file-type-icons 1.3.4 
highlight-selected 0.14.0 
minimap 4.29.9 
```

**Comment by execjosh** [comment]
Hmmm 🤔
